export const GET_STUDENTS = "GET_STUDENTS";
export const ADD_STUDENT = "ADD_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";

export const GET_COLLEGES = "GET_COLLEGES";
export const ADD_COLLEGE = "ADD_COLLEGE";
export const DELETE_COLLEGE = "DELETE_COLLEGE";

export const STUDENTS_LOADING = "STUDENTS_LOADING";
export const COLLEGES_LOADING = "COLLEGES_LOADING"
